#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmLogin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KTXSV")]
	public partial class QLKTXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCANBO_QL(CANBO_QL instance);
    partial void UpdateCANBO_QL(CANBO_QL instance);
    partial void DeleteCANBO_QL(CANBO_QL instance);
    partial void InsertPHONG(PHONG instance);
    partial void UpdatePHONG(PHONG instance);
    partial void DeletePHONG(PHONG instance);
    partial void InsertDAYPHONG(DAYPHONG instance);
    partial void UpdateDAYPHONG(DAYPHONG instance);
    partial void DeleteDAYPHONG(DAYPHONG instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertSINHVIEN(SINHVIEN instance);
    partial void UpdateSINHVIEN(SINHVIEN instance);
    partial void DeleteSINHVIEN(SINHVIEN instance);
    #endregion
		
		public QLKTXDataContext() : 
				base(global::FrmLogin.Properties.Settings.Default.KTXSVConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKTXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CANBO_QL> CANBO_QLs
		{
			get
			{
				return this.GetTable<CANBO_QL>();
			}
		}
		
		public System.Data.Linq.Table<PHONG> PHONGs
		{
			get
			{
				return this.GetTable<PHONG>();
			}
		}
		
		public System.Data.Linq.Table<DAYPHONG> DAYPHONGs
		{
			get
			{
				return this.GetTable<DAYPHONG>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<SINHVIEN> SINHVIENs
		{
			get
			{
				return this.GetTable<SINHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<vThongtinPhongg> vThongtinPhonggs
		{
			get
			{
				return this.GetTable<vThongtinPhongg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CANBO_QL")]
	public partial class CANBO_QL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACBQL;
		
		private string _TENCB;
		
		private string _DIACHI;
		
		private string _PHONG;
		
		private EntitySet<PHONG> _PHONGs;
		
		private EntitySet<DAYPHONG> _DAYPHONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACBQLChanging(string value);
    partial void OnMACBQLChanged();
    partial void OnTENCBChanging(string value);
    partial void OnTENCBChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnPHONGChanging(string value);
    partial void OnPHONGChanged();
    #endregion
		
		public CANBO_QL()
		{
			this._PHONGs = new EntitySet<PHONG>(new Action<PHONG>(this.attach_PHONGs), new Action<PHONG>(this.detach_PHONGs));
			this._DAYPHONGs = new EntitySet<DAYPHONG>(new Action<DAYPHONG>(this.attach_DAYPHONGs), new Action<DAYPHONG>(this.detach_DAYPHONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACBQL", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACBQL
		{
			get
			{
				return this._MACBQL;
			}
			set
			{
				if ((this._MACBQL != value))
				{
					this.OnMACBQLChanging(value);
					this.SendPropertyChanging();
					this._MACBQL = value;
					this.SendPropertyChanged("MACBQL");
					this.OnMACBQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENCB
		{
			get
			{
				return this._TENCB;
			}
			set
			{
				if ((this._TENCB != value))
				{
					this.OnTENCBChanging(value);
					this.SendPropertyChanging();
					this._TENCB = value;
					this.SendPropertyChanged("TENCB");
					this.OnTENCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONG", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string PHONG
		{
			get
			{
				return this._PHONG;
			}
			set
			{
				if ((this._PHONG != value))
				{
					this.OnPHONGChanging(value);
					this.SendPropertyChanging();
					this._PHONG = value;
					this.SendPropertyChanged("PHONG");
					this.OnPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CANBO_QL_PHONG", Storage="_PHONGs", ThisKey="MACBQL", OtherKey="NGUOIQUANLY")]
		public EntitySet<PHONG> PHONGs
		{
			get
			{
				return this._PHONGs;
			}
			set
			{
				this._PHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CANBO_QL_DAYPHONG", Storage="_DAYPHONGs", ThisKey="MACBQL", OtherKey="MANQL")]
		public EntitySet<DAYPHONG> DAYPHONGs
		{
			get
			{
				return this._DAYPHONGs;
			}
			set
			{
				this._DAYPHONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.CANBO_QL = this;
		}
		
		private void detach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.CANBO_QL = null;
		}
		
		private void attach_DAYPHONGs(DAYPHONG entity)
		{
			this.SendPropertyChanging();
			entity.CANBO_QL = this;
		}
		
		private void detach_DAYPHONGs(DAYPHONG entity)
		{
			this.SendPropertyChanging();
			entity.CANBO_QL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG")]
	public partial class PHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHONG;
		
		private string _MADAY;
		
		private string _TENPHONG;
		
		private string _NGUOIQUANLY;
		
		private System.Nullable<int> _SLToida;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
		private EntityRef<CANBO_QL> _CANBO_QL;
		
		private EntityRef<DAYPHONG> _DAYPHONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnMADAYChanging(string value);
    partial void OnMADAYChanged();
    partial void OnTENPHONGChanging(string value);
    partial void OnTENPHONGChanged();
    partial void OnNGUOIQUANLYChanging(string value);
    partial void OnNGUOIQUANLYChanged();
    partial void OnSLToidaChanging(System.Nullable<int> value);
    partial void OnSLToidaChanged();
    #endregion
		
		public PHONG()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			this._CANBO_QL = default(EntityRef<CANBO_QL>);
			this._DAYPHONG = default(EntityRef<DAYPHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHONG
		{
			get
			{
				return this._MAPHONG;
			}
			set
			{
				if ((this._MAPHONG != value))
				{
					this.OnMAPHONGChanging(value);
					this.SendPropertyChanging();
					this._MAPHONG = value;
					this.SendPropertyChanged("MAPHONG");
					this.OnMAPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADAY", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MADAY
		{
			get
			{
				return this._MADAY;
			}
			set
			{
				if ((this._MADAY != value))
				{
					if (this._DAYPHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADAYChanging(value);
					this.SendPropertyChanging();
					this._MADAY = value;
					this.SendPropertyChanged("MADAY");
					this.OnMADAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHONG", DbType="NVarChar(25)")]
		public string TENPHONG
		{
			get
			{
				return this._TENPHONG;
			}
			set
			{
				if ((this._TENPHONG != value))
				{
					this.OnTENPHONGChanging(value);
					this.SendPropertyChanging();
					this._TENPHONG = value;
					this.SendPropertyChanged("TENPHONG");
					this.OnTENPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOIQUANLY", DbType="VarChar(8)")]
		public string NGUOIQUANLY
		{
			get
			{
				return this._NGUOIQUANLY;
			}
			set
			{
				if ((this._NGUOIQUANLY != value))
				{
					if (this._CANBO_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNGUOIQUANLYChanging(value);
					this.SendPropertyChanging();
					this._NGUOIQUANLY = value;
					this.SendPropertyChanged("NGUOIQUANLY");
					this.OnNGUOIQUANLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLToida", DbType="Int")]
		public System.Nullable<int> SLToida
		{
			get
			{
				return this._SLToida;
			}
			set
			{
				if ((this._SLToida != value))
				{
					this.OnSLToidaChanging(value);
					this.SendPropertyChanging();
					this._SLToida = value;
					this.SendPropertyChanged("SLToida");
					this.OnSLToidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_SINHVIEN", Storage="_SINHVIENs", ThisKey="MAPHONG", OtherKey="PHONG")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CANBO_QL_PHONG", Storage="_CANBO_QL", ThisKey="NGUOIQUANLY", OtherKey="MACBQL", IsForeignKey=true)]
		public CANBO_QL CANBO_QL
		{
			get
			{
				return this._CANBO_QL.Entity;
			}
			set
			{
				CANBO_QL previousValue = this._CANBO_QL.Entity;
				if (((previousValue != value) 
							|| (this._CANBO_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CANBO_QL.Entity = null;
						previousValue.PHONGs.Remove(this);
					}
					this._CANBO_QL.Entity = value;
					if ((value != null))
					{
						value.PHONGs.Add(this);
						this._NGUOIQUANLY = value.MACBQL;
					}
					else
					{
						this._NGUOIQUANLY = default(string);
					}
					this.SendPropertyChanged("CANBO_QL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAYPHONG_PHONG", Storage="_DAYPHONG", ThisKey="MADAY", OtherKey="MADAY", IsForeignKey=true)]
		public DAYPHONG DAYPHONG
		{
			get
			{
				return this._DAYPHONG.Entity;
			}
			set
			{
				DAYPHONG previousValue = this._DAYPHONG.Entity;
				if (((previousValue != value) 
							|| (this._DAYPHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DAYPHONG.Entity = null;
						previousValue.PHONGs.Remove(this);
					}
					this._DAYPHONG.Entity = value;
					if ((value != null))
					{
						value.PHONGs.Add(this);
						this._MADAY = value.MADAY;
					}
					else
					{
						this._MADAY = default(string);
					}
					this.SendPropertyChanged("DAYPHONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG1 = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHONG1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAYPHONG")]
	public partial class DAYPHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADAY;
		
		private string _TENDAY;
		
		private int _SOLUONGPHONG;
		
		private string _MANQL;
		
		private EntitySet<PHONG> _PHONGs;
		
		private EntityRef<CANBO_QL> _CANBO_QL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADAYChanging(string value);
    partial void OnMADAYChanged();
    partial void OnTENDAYChanging(string value);
    partial void OnTENDAYChanged();
    partial void OnSOLUONGPHONGChanging(int value);
    partial void OnSOLUONGPHONGChanged();
    partial void OnMANQLChanging(string value);
    partial void OnMANQLChanged();
    #endregion
		
		public DAYPHONG()
		{
			this._PHONGs = new EntitySet<PHONG>(new Action<PHONG>(this.attach_PHONGs), new Action<PHONG>(this.detach_PHONGs));
			this._CANBO_QL = default(EntityRef<CANBO_QL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADAY", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADAY
		{
			get
			{
				return this._MADAY;
			}
			set
			{
				if ((this._MADAY != value))
				{
					this.OnMADAYChanging(value);
					this.SendPropertyChanging();
					this._MADAY = value;
					this.SendPropertyChanged("MADAY");
					this.OnMADAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDAY", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TENDAY
		{
			get
			{
				return this._TENDAY;
			}
			set
			{
				if ((this._TENDAY != value))
				{
					this.OnTENDAYChanging(value);
					this.SendPropertyChanging();
					this._TENDAY = value;
					this.SendPropertyChanged("TENDAY");
					this.OnTENDAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGPHONG", DbType="Int NOT NULL")]
		public int SOLUONGPHONG
		{
			get
			{
				return this._SOLUONGPHONG;
			}
			set
			{
				if ((this._SOLUONGPHONG != value))
				{
					this.OnSOLUONGPHONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGPHONG = value;
					this.SendPropertyChanged("SOLUONGPHONG");
					this.OnSOLUONGPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANQL", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string MANQL
		{
			get
			{
				return this._MANQL;
			}
			set
			{
				if ((this._MANQL != value))
				{
					if (this._CANBO_QL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANQLChanging(value);
					this.SendPropertyChanging();
					this._MANQL = value;
					this.SendPropertyChanged("MANQL");
					this.OnMANQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DAYPHONG_PHONG", Storage="_PHONGs", ThisKey="MADAY", OtherKey="MADAY")]
		public EntitySet<PHONG> PHONGs
		{
			get
			{
				return this._PHONGs;
			}
			set
			{
				this._PHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CANBO_QL_DAYPHONG", Storage="_CANBO_QL", ThisKey="MANQL", OtherKey="MACBQL", IsForeignKey=true)]
		public CANBO_QL CANBO_QL
		{
			get
			{
				return this._CANBO_QL.Entity;
			}
			set
			{
				CANBO_QL previousValue = this._CANBO_QL.Entity;
				if (((previousValue != value) 
							|| (this._CANBO_QL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CANBO_QL.Entity = null;
						previousValue.DAYPHONGs.Remove(this);
					}
					this._CANBO_QL.Entity = value;
					if ((value != null))
					{
						value.DAYPHONGs.Add(this);
						this._MANQL = value.MACBQL;
					}
					else
					{
						this._MANQL = default(string);
					}
					this.SendPropertyChanged("CANBO_QL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.DAYPHONG = this;
		}
		
		private void detach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.DAYPHONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHD;
		
		private string _TENHD;
		
		private System.Nullable<int> _TIENDIEN;
		
		private System.Nullable<int> _TIENNUOC;
		
		private System.Nullable<int> _TIENPHONG;
		
		private EntitySet<SINHVIEN> _SINHVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnTENHDChanging(string value);
    partial void OnTENHDChanged();
    partial void OnTIENDIENChanging(System.Nullable<int> value);
    partial void OnTIENDIENChanged();
    partial void OnTIENNUOCChanging(System.Nullable<int> value);
    partial void OnTIENNUOCChanged();
    partial void OnTIENPHONGChanging(System.Nullable<int> value);
    partial void OnTIENPHONGChanged();
    #endregion
		
		public HOPDONG()
		{
			this._SINHVIENs = new EntitySet<SINHVIEN>(new Action<SINHVIEN>(this.attach_SINHVIENs), new Action<SINHVIEN>(this.detach_SINHVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHD", DbType="NVarChar(20)")]
		public string TENHD
		{
			get
			{
				return this._TENHD;
			}
			set
			{
				if ((this._TENHD != value))
				{
					this.OnTENHDChanging(value);
					this.SendPropertyChanging();
					this._TENHD = value;
					this.SendPropertyChanged("TENHD");
					this.OnTENHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENDIEN", DbType="Int")]
		public System.Nullable<int> TIENDIEN
		{
			get
			{
				return this._TIENDIEN;
			}
			set
			{
				if ((this._TIENDIEN != value))
				{
					this.OnTIENDIENChanging(value);
					this.SendPropertyChanging();
					this._TIENDIEN = value;
					this.SendPropertyChanged("TIENDIEN");
					this.OnTIENDIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENNUOC", DbType="Int")]
		public System.Nullable<int> TIENNUOC
		{
			get
			{
				return this._TIENNUOC;
			}
			set
			{
				if ((this._TIENNUOC != value))
				{
					this.OnTIENNUOCChanging(value);
					this.SendPropertyChanging();
					this._TIENNUOC = value;
					this.SendPropertyChanged("TIENNUOC");
					this.OnTIENNUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENPHONG", DbType="Int")]
		public System.Nullable<int> TIENPHONG
		{
			get
			{
				return this._TIENPHONG;
			}
			set
			{
				if ((this._TIENPHONG != value))
				{
					this.OnTIENPHONGChanging(value);
					this.SendPropertyChanging();
					this._TIENPHONG = value;
					this.SendPropertyChanged("TIENPHONG");
					this.OnTIENPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_SINHVIEN", Storage="_SINHVIENs", ThisKey="MAHD", OtherKey="MAHD")]
		public EntitySet<SINHVIEN> SINHVIENs
		{
			get
			{
				return this._SINHVIENs;
			}
			set
			{
				this._SINHVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_SINHVIENs(SINHVIEN entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA;
		
		private string _HOTEN;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAChanging(int value);
    partial void OnMAChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnPhanQuyenChanging(System.Nullable<bool> value);
    partial void OnPhanQuyenChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA
		{
			get
			{
				return this._MA;
			}
			set
			{
				if ((this._MA != value))
				{
					this.OnMAChanging(value);
					this.SendPropertyChanging();
					this._MA = value;
					this.SendPropertyChanged("MA");
					this.OnMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="Bit")]
		public System.Nullable<bool> PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this.OnPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen = value;
					this.SendPropertyChanged("PhanQuyen");
					this.OnPhanQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINHVIEN")]
	public partial class SINHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASV;
		
		private string _TENSV;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _PHONG;
		
		private System.Nullable<System.DateTime> _NGAYVAOKTX;
		
		private System.Nullable<System.DateTime> _NGAYRAKTX;
		
		private string _MAHD;
		
		private string _GIOITINH;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
		private EntityRef<PHONG> _PHONG1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASVChanging(string value);
    partial void OnMASVChanged();
    partial void OnTENSVChanging(string value);
    partial void OnTENSVChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnPHONGChanging(string value);
    partial void OnPHONGChanged();
    partial void OnNGAYVAOKTXChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOKTXChanged();
    partial void OnNGAYRAKTXChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYRAKTXChanged();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    #endregion
		
		public SINHVIEN()
		{
			this._HOPDONG = default(EntityRef<HOPDONG>);
			this._PHONG1 = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASV", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASV
		{
			get
			{
				return this._MASV;
			}
			set
			{
				if ((this._MASV != value))
				{
					this.OnMASVChanging(value);
					this.SendPropertyChanging();
					this._MASV = value;
					this.SendPropertyChanged("MASV");
					this.OnMASVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENSV
		{
			get
			{
				return this._TENSV;
			}
			set
			{
				if ((this._TENSV != value))
				{
					this.OnTENSVChanging(value);
					this.SendPropertyChanging();
					this._TENSV = value;
					this.SendPropertyChanged("TENSV");
					this.OnTENSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONG", DbType="VarChar(8)")]
		public string PHONG
		{
			get
			{
				return this._PHONG;
			}
			set
			{
				if ((this._PHONG != value))
				{
					if (this._PHONG1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPHONGChanging(value);
					this.SendPropertyChanging();
					this._PHONG = value;
					this.SendPropertyChanged("PHONG");
					this.OnPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAOKTX", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYVAOKTX
		{
			get
			{
				return this._NGAYVAOKTX;
			}
			set
			{
				if ((this._NGAYVAOKTX != value))
				{
					this.OnNGAYVAOKTXChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAOKTX = value;
					this.SendPropertyChanged("NGAYVAOKTX");
					this.OnNGAYVAOKTXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYRAKTX", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYRAKTX
		{
			get
			{
				return this._NGAYRAKTX;
			}
			set
			{
				if ((this._NGAYRAKTX != value))
				{
					this.OnNGAYRAKTXChanging(value);
					this.SendPropertyChanging();
					this._NGAYRAKTX = value;
					this.SendPropertyChanged("NGAYRAKTX");
					this.OnNGAYRAKTXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="VarChar(8)")]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_SINHVIEN", Storage="_HOPDONG", ThisKey="MAHD", OtherKey="MAHD", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._MAHD = value.MAHD;
					}
					else
					{
						this._MAHD = default(string);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_SINHVIEN", Storage="_PHONG1", ThisKey="PHONG", OtherKey="MAPHONG", IsForeignKey=true)]
		public PHONG PHONG1
		{
			get
			{
				return this._PHONG1.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG1.Entity;
				if (((previousValue != value) 
							|| (this._PHONG1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG1.Entity = null;
						previousValue.SINHVIENs.Remove(this);
					}
					this._PHONG1.Entity = value;
					if ((value != null))
					{
						value.SINHVIENs.Add(this);
						this._PHONG = value.MAPHONG;
					}
					else
					{
						this._PHONG = default(string);
					}
					this.SendPropertyChanged("PHONG1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vThongtinPhongg")]
	public partial class vThongtinPhongg
	{
		
		private string _TENPHONG;
		
		private string _MADAY;
		
		private string _NGUOIQUANLY;
		
		private System.Nullable<int> _Soluong;
		
		public vThongtinPhongg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHONG", DbType="NVarChar(25)")]
		public string TENPHONG
		{
			get
			{
				return this._TENPHONG;
			}
			set
			{
				if ((this._TENPHONG != value))
				{
					this._TENPHONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADAY", DbType="VarChar(8)")]
		public string MADAY
		{
			get
			{
				return this._MADAY;
			}
			set
			{
				if ((this._MADAY != value))
				{
					this._MADAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOIQUANLY", DbType="VarChar(8)")]
		public string NGUOIQUANLY
		{
			get
			{
				return this._NGUOIQUANLY;
			}
			set
			{
				if ((this._NGUOIQUANLY != value))
				{
					this._NGUOIQUANLY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this._Soluong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
